### ISSUE TITLE
smallcheck-1.1.1 doesn't compile with current GHC head snapshot

### ISSUE THREAD

**Issue by peti** [feuerbach/smallcheck#28]
Citing from http://hydra.cryp.to/build/794575/nixlog/13/raw:

    Test/SmallCheck/Property.hs:187:10:
        Could not deduce (Monad n)
          arising from the superclasses of an instance declaration
        from the context: (Monad m, m ~ n)
          bound by the instance declaration
          at Test/SmallCheck/Property.hs:187:10-52
        Possible fix:
          add (Monad n) to the context of the instance declaration
        In the instance declaration for ‘Testable n (Property m)’

**Comment by feuerbach** [comment]
Reported as a ghc regression: https://ghc.haskell.org/trac/ghc/ticket/10423

**Comment by feuerbach** [comment]
Should be fixed in ghc now.
