### ISSUE TITLE
Port some convenience list functions from QuickCheck

### ISSUE THREAD

**Issue by rpglover64** [feuerbach/smallcheck#29]
I have a function which takes a list as an argument, and I would like to test that its result does not depend on the order of the list (`sort` comes to mind as a realistic example). QuickCheck has a function to do this: [`shuffle`](http://hackage.haskell.org/package/QuickCheck-2.8.1/docs/Test-QuickCheck-Gen.html#v:shuffle).

I have thrown together a simple implementation for SmallCheck [here](https://gist.github.com/rpglover64/740040c28b725cd93337).

**Comment by feuerbach** [comment]
This is unnecessarily complicated. There's `Data.List.permutations`.

**Comment by rpglover64** [comment]
Just `permutations` lacks the (somewhat desirable) property that the number of permutations considered varies with `Depth`; that said, I guess either `(\x -> generate (flip take x)) . permutations` or `(\x -> generate (flip take x . (2^)) . permutations` would work.
