### ISSUE TITLE
Smallcheck defines an orphan which overlaps `Show (a -> b)` instance from base

### ISSUE THREAD

**Issue by mgsloan** [feuerbach/smallcheck#35]
https://hackage.haskell.org/package/base-4.8.2.0/docs/Text-Show-Functions.html

```
/home/mgsloan/fpco/stack/src/Stack/Types/Nix.hs:33:13:
    Overlapping instances for Show
                                (Maybe Resolver -> Maybe CompilerVersion -> Text)
      arising from the sixth field of ‘NixOpts’
        (type ‘Maybe Resolver -> Maybe CompilerVersion -> Text’)
    Matching instances:
      instance [safe] Show (a -> b) -- Defined in ‘Text.Show.Functions’
      instance [overlap ok] (Test.SmallCheck.Series.Serial
                               Data.Functor.Identity.Identity a,
                             Show a, Show b) =>
                            Show (a -> b)
        -- Defined in ‘Test.SmallCheck.Series’
    When deriving the instance for (Show NixOpts)
```

**Comment by mgsloan** [comment]
For now I will hack around by introducing a newtype.

**Comment by mgsloan** [comment]
Also, I generally like being warned when I try to Show functions.  It's unfortunate to need to choose between that checking and using smallcheck.

Perhaps use the same trick that quickcheck uses - `Blind`?

**Comment by feuerbach** [comment]
See also #11.

I don't have time to investigate this at the moment, but if you have a solution in mind which is backwards compatible and could prepare a pull request, I'm all for it.

**Comment by mgsloan** [comment]
Gotcha, closing this as a dupe of that.  I don't think there can be any backwards compatible solutions.
