### ISSUE TITLE
Serial instance for base types

### ISSUE THREAD

**Issue by Profpatsch** [feuerbach/smallcheck#37]
Having only default Prelude instances is kind of a deal-breaker.
Prelude is in base, so nothing should speak against providing instances for all of its types.

**Comment by Profpatsch** [comment]
I tried myself at an instance for Natural, there is probably a better way than `fromInteger . toInteger`.

```haskell
instance Monad m => Serial m Natural where
  series = generate $ \n -> [1..(fromInteger $ toInteger n)]
```

**Comment by feuerbach** [comment]
The instances for `Word` and `Natural` are now in.

I don't think having an instance for every single type in base is a worthy goal, but if you need some other specific instances, we can discuss it.
