### ISSUE TITLE
Show the bad tests(the ones which didn't meet the ==> condition) even on success

### ISSUE THREAD

**Issue by abnud1** [feuerbach/smallcheck#38]
I often see this result from checking a property which has `==>` somewhere in it : 

> Completed n tests without failure.
   But w did not meet ==> condition.

Now when `w==n`, I would like to see some of the tests to know why wasn't the `==>` met, so maybe print them ? or save them in a log if `w` is big.

**Comment by feuerbach** [comment]
If `w==n`, then every single one did not meet the condition. You can just use `list` to see the values that SmallCheck generates.
