### ISSUE TITLE
Could not find module Numeric.Natural in GHC 7.8

### ISSUE THREAD

**Issue by Bodigrim** [feuerbach/smallcheck#41]
`smallcheck-1.1.3` fails to build with GHC 7.8 (https://api.travis-ci.org/v3/job/317785501/log.txt), because `Numeric.Natural` appeared in `base` only in GHC 7.10. I suggest either to bump minimal bound of `base`, or to add

```
if impl(ghc < 7.10)
  build-depends: nats
```

**Comment by feuerbach** [comment]
Should be fixed now, thanks.
