### ISSUE TITLE
Smallcheck fails to build due to the Safe pragma

### ISSUE THREAD

**Issue by recursion-ninja** [feuerbach/smallcheck#44]
Smallcheck fails to build due to the `Safe` pragma. The `logict` dependency is the problem. Adding appropriate version bounds would likely resolve the issue. 

You can see logs of an example failed compilation [here](https://travis-ci.org/recursion-ninja/bv-little/jobs/560693267).

**Comment by feuerbach** [comment]
Yep, see https://github.com/Bodigrim/logict/issues/3

@Bodigrim could you please upload the new version of logict that fixes the issue?

**Comment by Bodigrim** [comment]
Sure, will do later today.

**Comment by Bodigrim** [comment]
Done.
